-- NA Inbound GR - Full detail pull from SQ_841_INBOUND_V
-- Source: ORACLE_ERP.SCM.SQ_841_INBOUND_V
-- Facilities: CVU (US), IMC (Canada), IMU (Canada)
-- Filter: TENANT IN ('SQ','SQ1'), REMARKS = 'STAT'
-- Schedule: Daily at 4:00 AM PST
-- History: Data available from 2019-07-02

SELECT
    TO_CHAR(TO_DATE(ADJUSTMENT_DATE), 'YYYY-MM-DD') AS ADJUSTMENT_DATE,
    FACILILTY_ID AS FACILITY_ID,
    ITEM_CODE,
    ITEM_DESCRIPTION,
    PRODUCT_NAME,
    CLIENT_CODE,
    ADJUSTMENT_ID,
    COALESCE(AVL_QUANTITY, 0) AS AVL_QUANTITY,
    COALESCE(UNAVL_QUANTITY, 0) AS UNAVL_QUANTITY,
    COALESCE(RETURN_QUANTITY, 0) AS RETURN_QUANTITY,
    COALESCE(STD_COST, 0) AS STD_COST,
    COALESCE(EXTENDED_COST, 0) AS EXTENDED_COST,
    FILE_NAME,
    PROCESS_FLAG
FROM ORACLE_ERP.SCM.SQ_841_INBOUND_V
WHERE TENANT IN ('SQ','SQ1')
  AND FACILILTY_ID IN ('CVU', 'IMC', 'IMU')
  AND REMARKS = 'STAT'
  AND ADJUSTMENT_DATE >= DATEADD('day', -{lookback_days}, CURRENT_DATE())
ORDER BY ADJUSTMENT_DATE DESC, FACILILTY_ID, ITEM_CODE
